defaults:
  - embedding: default
  - optimizer: adam
  - transformer: residual

_recursive_: False
_target_: ens_transformer.models.PPNNet
n_transformers: 1
output_channels: 2
loss_str: crps
learning_rate: ${learning_rate}
